#定义分页时必须传送的参数名
page:
  #每页大小，必要属性
  size: pageSize
  #当前页，必要属性
  num: pageNum
  #顺序排列,降序或逆序，默认为ASC，可选desc
  order: order
  #选择排序的字段，按下列定义顺序，例如：该参数值为0，那么选中customer中的name排序
  clause: clause

#定义customer接收的分页条件查询参数名
#字段名数组：cust_name,cust_address,cust_phone,cust_bank
customer:
  name: custName
  address: custAddress
  phone: custPhone
  bank: custBank

#排序：字段名数组：goods_name,goods_place
#定义goods接收的分页条件查询参数名
goods:
  name: goodsName
  place: goodsPlace

#排序：字段名数组：supp_name,supp_address,supp_phone,supp_bank
#定义supplier接收的分页条件查询参数名
supplier:
  name: suppName
  address: suppAddress
  phone: suppPhone
  bank: suppBank

#排序：字段名数组：user_name,user_phone,user_gender,user_type
#定义user接收的分页条件查询参数名
user:
  name: userName
  gender: userGender

#排序：字段名称数组：rece_createtime,rece_sum,rece_state
#定义receipt接收的分页条件查询参数名
receipt:
  start: startTime
  end: endTime
  suppId: suppId
  userId: userId
  state: state

#排序:字段名称数组:sale_createtime,sale_sum,sale_state
#定义sale接收的分页条件查询参数名
sale:
  start: startTime
  end: endTime
  custId: custId
  userId: userId
  state: state

#排序:字段名称数组:rece_id,rece_num,fresh,remain
#定义store接收的分页条件查询参数名
store:
  remain: remain
  receId: receId
  goodsId: goodsId
  start: startTime
  end: endTime